"""
Django settings for Carbomica_app project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '(j=&pjt1#^j(005!8vb!)%=^o2#=!76*r0w*%wjefp__nrmc%f')

# Debug is off unless explicitly enabled
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Localhost + Heroku legacy + Firebase Hosting + Cloud Run
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.herokuapp.com',
    'carbomica-tool.web.app',
    'carbomica-tool.firebaseapp.com',
    '.run.app',          # Cloud Run preview URLs (*.run.app)
]

# Allow Django test client's default HTTP_HOST in development/CI
if DEBUG or os.getenv('DJANGO_TESTING') == '1':
    ALLOWED_HOSTS += ['testserver']

# Trust HTTPS from Firebase Hosting and Cloud Run load balancer
CSRF_TRUSTED_ORIGINS = [
    'https://carbomica-tool.web.app',
    'https://carbomica-tool.firebaseapp.com',
    'https://*.run.app',
]

# Cloud Run sets X-Forwarded-Proto; tell Django to trust it for HTTPS detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Firebase Hosting sets X-Forwarded-Host to the public domain (carbomica-tool.web.app)
# before proxying to Cloud Run. This ensures Django builds OAuth redirect URIs
# using the Firebase URL, not the raw Cloud Run URL.
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
    "appname",
    "crispy_forms",
    "crispy_bootstrap5",
    "whitenoise",
    # Google / social auth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

SITE_ID = 1

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "Carbomica_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'appname/templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Carbomica_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        # conn_max_age=0 required for Supabase transaction pooler (port 6543):
        # the pooler closes server-side connections after each transaction, so
        # persistent connections cause session lookups to fail on Cloud Run.
        conn_max_age=0,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Security settings for production
# SECURE_SSL_REDIRECT stays False — Cloud Run / Firebase terminates TLS at
# the load balancer before requests reach Django (enabling it causes redirect loops).
# SECURE_HSTS_SECONDS is also omitted because the LB enforces HTTPS already.
# Django's deploy check warnings for these two are suppressed via SILENCED_SYSTEM_CHECKS.
SECURE_SSL_REDIRECT = False
# Firebase Hosting CDN strips all cookies except those named '__session' or
# prefixed '__Host-'. Rename Django's session cookie so Firebase passes it through.
SESSION_COOKIE_NAME = '__session'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

SILENCED_SYSTEM_CHECKS = ['security.W004', 'security.W008']

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# django-allauth — Google OAuth configuration
#
# To activate Google login:
#   1. Go to console.cloud.google.com → APIs & Services → Credentials
#   2. Create an OAuth 2.0 Client ID (Web application)
#   3. Add Authorised redirect URI: https://carbomica-tool.web.app/accounts/google/login/callback/
#      (and http://localhost:8000/accounts/google/login/callback/ for local dev)
#   4. Set GOOGLE_CLIENT_ID and GOOGLE_SECRET in your .env file or Cloud Run secrets
#   5. In Django admin → Sites → change example.com to carbomica-tool.web.app
#   6. In Django admin → Social Applications → add Google app with above credentials
# ---------------------------------------------------------------------------
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'   # land on login page after sign-out
LOGIN_URL = 'account_login'                # used by @login_required decorator

# ── allauth account settings (Google-only — no email/password) ──
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'        # skip email confirmation
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'

# Disable regular username/password signup (Google only)
ACCOUNT_ALLOW_REGISTRATION = False

# ── Social account settings ──
SOCIALACCOUNT_AUTO_SIGNUP = True           # auto-create user on first Google login
SOCIALACCOUNT_LOGIN_ON_GET = True          # skip intermediate confirmation page
SOCIALACCOUNT_EMAIL_REQUIRED = True        # require email from Google

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret':    os.getenv('GOOGLE_SECRET', ''),
            'key':       '',
        },
    }
}
