# Generated by Django 5.0.1 on 2024-01-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissiondata",
            name="anaesthetic_gases",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="business_travel",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="liquid_fuel",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="medical_inhalers",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="refrigeration_gases",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="vehicle_fuel_owned",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="waste_management",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="facilityintervention",
            name="implementation_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="facilityintervention",
            name="maintenance_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="bottled_gas",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="grid_electricity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="grid_gas",
            field=models.FloatField(default=0.0),
        ),
    ]
