# Generated by Django 5.0.1 on 2024-01-18 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0002_emissiondata_anaesthetic_gases_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="effectsize",
            options={
                "ordering": ["facility__display_name"],
                "verbose_name": "Effect Size",
                "verbose_name_plural": "Effect Sizes",
            },
        ),
        migrations.AlterModelOptions(
            name="emissiondata",
            options={
                "ordering": ["-emission_source__display_name"],
                "verbose_name": "Emission Data",
                "verbose_name_plural": "Emission Data Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="emissionsource",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Emission Source",
                "verbose_name_plural": "Emission Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.AlterModelOptions(
            name="facilityintervention",
            options={
                "ordering": ["facility__display_name"],
                "verbose_name": "Facility Intervention",
                "verbose_name_plural": "Facility Interventions",
            },
        ),
        migrations.AlterModelOptions(
            name="implementationcost",
            options={
                "ordering": ["facility__display_name"],
                "verbose_name": "Implementation Cost",
                "verbose_name_plural": "Implementation Costs",
            },
        ),
        migrations.AlterModelOptions(
            name="intervention",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancecost",
            options={
                "ordering": ["facility__display_name"],
                "verbose_name": "Maintenance Cost",
                "verbose_name_plural": "Maintenance Costs",
            },
        ),
        migrations.RemoveField(
            model_name="emissiondata",
            name="facility",
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="emission_source",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emission_data",
                to="appname.emissionsource",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionsource",
            name="facility",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emission_sources",
                to="appname.facility",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="effectsize",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="effect_sizes",
                to="appname.facility",
            ),
        ),
        migrations.AlterField(
            model_name="effectsize",
            name="recycling_waste_segregation",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="effectsize",
            name="solar_system_installation",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="anaesthetic_gases",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="bottled_gas",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="business_travel",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="grid_electricity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="grid_gas",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="liquid_fuel",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="medical_inhalers",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="refrigeration_gases",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="vehicle_fuel_owned",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="emissiondata",
            name="waste_management",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="facilityintervention",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_interventions",
                to="appname.facility",
            ),
        ),
        migrations.AlterField(
            model_name="facilityintervention",
            name="implementation_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="facilityintervention",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_interventions",
                to="appname.intervention",
            ),
        ),
        migrations.AlterField(
            model_name="facilityintervention",
            name="maintenance_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="implementationcost",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="implementation_costs",
                to="appname.facility",
            ),
        ),
        migrations.AlterField(
            model_name="implementationcost",
            name="recycling_waste_segregation",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="implementationcost",
            name="solar_system_installation",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="maintenancecost",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_costs",
                to="appname.facility",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancecost",
            name="recycling_waste_segregation",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="maintenancecost",
            name="solar_system_installation",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
