# Generated by Django 5.1.4 on 2025-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0004_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planned", "Planned"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Planned",
                max_length=50,
            ),
        ),
    ]
