# Generated by Django 5.1.4 on 2025-01-12 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0005_intervention_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissiondata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
