# Generated by Django 5.1.4 on 2025-01-12 17:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0006_emissiondata_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityintervention",
            name="annual_savings",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="facilityintervention",
            name="emission_reduction_achieved",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Actual emission reduction achieved in tCO2e",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="facilityintervention",
            name="implementation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facilityintervention",
            name="roi",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Return on Investment percentage",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="emission_reduction_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Expected percentage reduction in emissions",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="energy_savings",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Expected annual energy savings in kWh",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="payback_period",
            field=models.IntegerField(
                default=0,
                help_text="Expected payback period in months",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="facilityintervention",
            name="implementation_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="facilityintervention",
            name="maintenance_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.CreateModel(
            name="InterventionEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_size",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_effects",
                        to="appname.facility",
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="appname.intervention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention Effect",
                "verbose_name_plural": "Intervention Effects",
                "ordering": ["facility__display_name"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "target_reduction",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target emission reduction percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Optimized", "Optimized"),
                            ("Implemented", "Implemented"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_scenarios",
                        to="appname.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimization Scenario",
                "verbose_name_plural": "Optimization Scenarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("expected_roi", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "emission_reduction",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "implementation_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "annual_savings",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("payback_months", models.IntegerField()),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appname.intervention",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="appname.optimizationscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimization Result",
                "verbose_name_plural": "Optimization Results",
                "ordering": ["priority"],
            },
        ),
    ]
