# Generated by Django 5.2.1 on 2026-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0007_facilityintervention_annual_savings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="country",
            field=models.CharField(
                choices=[
                    ("ZW", "Zimbabwe"),
                    ("ZA", "South Africa"),
                    ("KE", "Kenya"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("district_hospital", "District Hospital"),
                    ("provincial_hospital", "Provincial Hospital"),
                    ("central_hospital", "Central Hospital"),
                    ("health_centre", "Health Centre / Clinic"),
                    ("maternity_unit", "Maternity Unit"),
                    ("other", "Other"),
                ],
                default="district_hospital",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="sdg_goals",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated SDG numbers this intervention contributes to (e.g. '3,7,13')",
                max_length=50,
            ),
        ),
    ]
