# Generated by Django 5.2.1 on 2026-04-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0009_emissiondata_contractor_logistics_facility_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="target_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated EmissionData field names this intervention targets (e.g. 'grid_electricity' or 'grid_electricity,vehicle_fuel_owned'). Used by the optimizer to apply reductions to the correct emission category.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organisations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can access all facilities in this organisation.",
                        related_name="organisations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation this facility belongs to. All org members can access it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facilities",
                to="appname.organisation",
            ),
        ),
    ]
