# Generated by Django 5.2.1 on 2026-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0010_organisation_and_intervention_target_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityintervention",
            name="cost_source",
            field=models.CharField(
                choices=[
                    ("USER", "User-supplied"),
                    ("DEFAULT", "Library default"),
                    ("PLACEHOLDER", "Placeholder median"),
                ],
                default="USER",
                help_text="Provenance of cost values — used for rollback and 'verify before reporting' UI badges.",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityintervention",
            constraint=models.UniqueConstraint(
                fields=("facility", "intervention"), name="uniq_facility_intervention"
            ),
        ),
    ]
