# Generated by Django 5.2.1 on 2026-06-10 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0011_facilityintervention_cost_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optimizationscenario",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum capital (USD) — leave blank when using a reduction target",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="optimizationscenario",
            name="target_reduction",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target emission reduction percentage — leave blank when using a budget",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
