# Generated by Django 5.2.1 on 2026-05-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0011_facilityintervention_cost_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="sector",
            field=models.CharField(
                choices=[
                    ("clinical", "Clinical / Healthcare"),
                    ("research", "Research / Academic"),
                    ("ngo", "NGO / Non-profit"),
                    ("education", "Education"),
                    ("government", "Government / Public Authority"),
                    ("business", "Business / Commercial"),
                    ("other", "Other"),
                ],
                default="clinical",
                help_text="Higher-level grouping. Used for sector-appropriate intervention curation and grant-report templates.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="country",
            field=models.CharField(
                choices=[
                    ("ZW", "Zimbabwe"),
                    ("ZA", "South Africa"),
                    ("KE", "Kenya"),
                    ("TZ", "Tanzania"),
                    ("UG", "Uganda"),
                    ("NG", "Nigeria"),
                    ("GH", "Ghana"),
                    ("IN", "India"),
                    ("BD", "Bangladesh"),
                    ("GB", "United Kingdom"),
                    ("US", "United States"),
                    ("EU", "European Union (avg)"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("district_hospital", "District Hospital"),
                    ("provincial_hospital", "Provincial Hospital"),
                    ("central_hospital", "Central Hospital"),
                    ("health_centre", "Health Centre / Clinic"),
                    ("community_clinic", "Community Clinic"),
                    ("specialty_clinic", "Specialty Clinic (dental, eye, etc.)"),
                    ("maternity_unit", "Maternity Unit"),
                    ("research_office", "Research Organisation Office"),
                    ("university_lab", "University Research Lab"),
                    ("university_dept", "University Department / Faculty"),
                    ("ngo_office", "NGO Headquarters Office"),
                    ("ngo_field_office", "NGO Field Office"),
                    ("school", "School"),
                    ("govt_office", "Government Office"),
                    ("regional_health_authority", "Regional Health Authority"),
                    ("ministry", "Ministry / Department"),
                    ("sme_office", "Small / Medium Business Office"),
                    ("corporate_office", "Corporate Office"),
                    ("factory", "Factory / Manufacturing"),
                    ("warehouse", "Warehouse / Distribution"),
                    ("other", "Other"),
                ],
                default="district_hospital",
                max_length=50,
            ),
        ),
    ]
