# Generated by Django 5.1.4 on 2026-08-06 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0012_alter_optimizationscenario_budget_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="country",
            field=models.CharField(
                choices=[
                    ("ZW", "Zimbabwe"),
                    ("ZA", "South Africa"),
                    ("KE", "Kenya"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Used for the electricity emission factor in organisational reporting.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrganisationEmissionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Reporting year the entry belongs to (e.g. 2026)."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("flights", "Flights — air travel"),
                            ("fleet_fuel", "Vehicle fleet fuel"),
                            ("grid_electricity", "Office electricity"),
                            ("commuting", "Staff commuting"),
                            (
                                "procurement",
                                "Procurement & services (pre-calculated tCO2e)",
                            ),
                            ("other", "Other (pre-calculated tCO2e)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in the category unit (passenger-km, litres, kWh, km, or tCO2e).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "JNB-LHR return x3, consortium annual meeting"',
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_emission_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_entries",
                        to="appname.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisational Emission Entry",
                "verbose_name_plural": "Organisational Emission Entries",
                "ordering": ["-year", "category", "-created_at"],
            },
        ),
    ]
