# Generated by Django 5.1.4 on 2026-08-07 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0012_facility_sector_alter_facility_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissiondata",
            name="flights",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Scope 3 — passenger-km flown for work travel (conferences, fieldwork, meetings).",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="emissiondata",
            name="lab_consumables",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Scope 3 — annual spend (USD) on lab consumables, reagents and equipment procurement. Converted with spend-based EEIO factors.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="applicable_sectors",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated Facility sector keys this intervention applies to (e.g. 'clinical'). Empty = applies to every sector.",
                max_length=100,
            ),
        ),
    ]
