# Generated by Django 5.1.4 on 2026-08-06 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0013_organisation_country_organisationemissionentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OffsetPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Reporting year the credits offset."
                    ),
                ),
                (
                    "credits_tco2e",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Credits purchased (1 credit = 1 tCO2e).",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text='e.g. "Tree Planting in South African Townships (Verra #720)" or "GreenPop".',
                        max_length=200,
                    ),
                ),
                (
                    "registry_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Registry serial / retirement reference for audit evidence.",
                        max_length=255,
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost (USD), optional.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Tick once the credits are retired on the registry.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offset_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offset_purchases",
                        to="appname.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offset Purchase",
                "verbose_name_plural": "Offset Purchases",
                "ordering": ["-year", "-created_at"],
            },
        ),
    ]
