# Generated by Django 5.1.4 on 2026-09-30 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0013_emissiondata_flights_emissiondata_lab_consumables_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("consortium", "Consortium / umbrella body"),
                    ("division", "Division / grouping"),
                    ("entity", "Research entity / institute / unit"),
                    ("programme", "Programme / team"),
                ],
                default="entity",
                help_text="Where this sits in the hierarchy. Affects roll-up reporting only.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The organisation this one sits under. Blank for a top-level body.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="appname.organisation",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text='Acronym shown in compact views, e.g. "PHRU", "VIDA".',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can access all facilities in this organisation and every organisation beneath it.",
                related_name="organisations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
