# Generated by Django 5.1.4 on 2026-08-06 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0014_offsetpurchase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offsetpurchase",
            name="registry",
            field=models.CharField(
                choices=[
                    ("verra", "Verra (VCS)"),
                    ("gold_standard", "Gold Standard"),
                    ("plan_vivo", "Plan Vivo"),
                    ("woodland_carbon_code", "Woodland Carbon Code"),
                    ("other", "Other / not yet accredited"),
                ],
                default="verra",
                help_text="Accreditation standard. The Wellcome environmental sustainability funding policy requires third party accredited carbon credits (for example Gold Standard, Verra, Woodland Carbon Code or Plan Vivo).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="wellcome_grant_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Wellcome grant reference this organisation reports under (e.g. 336423/Z/25/Z).",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ReductionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baseline_year", models.PositiveIntegerField()),
                ("target_year", models.PositiveIntegerField()),
                (
                    "reduction_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent reduction on the baseline year total by the target year.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reduction_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reduction_targets",
                        to="appname.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reduction Target",
                "verbose_name_plural": "Reduction Targets",
                "ordering": ["-created_at"],
            },
        ),
    ]
