# Generated by Django 5.1.4 on 2026-09-30 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0014_organisation_org_type_organisation_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Key into modeling.PROCUREMENT_CATEGORIES. Unrecognised categories are stored as OTHER at import.",
                        max_length=40,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Captured for future supplier-level comparison. Not used in the calculation.",
                        max_length=255,
                    ),
                ),
                (
                    "spend_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Spend for this line in USD.",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CSV", "Imported from spend export"),
                            ("MANUAL", "Entered by hand"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emission_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_lines",
                        to="appname.emissiondata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Line",
                "verbose_name_plural": "Procurement Lines",
                "ordering": ["-spend_usd"],
                "indexes": [
                    models.Index(
                        fields=["emission_data", "category"],
                        name="appname_pro_emissio_f252e0_idx",
                    )
                ],
            },
        ),
    ]
