# Generated by Django 5.1.4 on 2026-09-30 10:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0015_procurementline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "grant_reference",
                    models.CharField(
                        blank=True,
                        help_text='The funder\'s award number, e.g. "225000/Z/22/Z".',
                        max_length=100,
                    ),
                ),
                (
                    "funder",
                    models.CharField(
                        choices=[
                            ("wellcome", "Wellcome Trust"),
                            ("nih", "NIH"),
                            ("ukri", "UKRI"),
                            ("gates", "Gates Foundation"),
                            ("eu", "European Commission"),
                            ("samrc", "South African MRC"),
                            ("nrf", "National Research Foundation (SA)"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "funder_other",
                    models.CharField(
                        blank=True,
                        help_text='Funder name when "Other" is selected.',
                        max_length=200,
                    ),
                ),
                (
                    "principal_investigator",
                    models.CharField(blank=True, max_length=200),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "budget_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total award value in USD.",
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "allocation_basis",
                    models.CharField(
                        choices=[
                            ("fte", "Staff FTE share"),
                            ("budget", "Share of site budget"),
                            ("space", "Share of floor / bench space"),
                            ("stated", "Directly stated share"),
                        ],
                        default="fte",
                        help_text="How shared site emissions are apportioned to this award.",
                        max_length=20,
                    ),
                ),
                (
                    "allocation_note",
                    models.TextField(
                        blank=True,
                        help_text='The auditable record behind the shares — e.g. "3.2 FTE of 41.0 FTE at the Bara laboratory, from the 2024 timesheet return". Reproduced on the funder report.',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lead entity holding the award.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="appname.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="procurementline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Award this purchase was charged to. Tagged lines are attributed to that award in full rather than apportioned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procurement_lines",
                to="appname.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_pct",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Percentage of this site's shared emissions attributable to the award.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "basis_note",
                    models.CharField(
                        blank=True,
                        help_text='Evidence for this share, e.g. "3.2 of 41.0 FTE".',
                        max_length=255,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_sites",
                        to="appname.facility",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="appname.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Site",
                "verbose_name_plural": "Project Sites",
                "ordering": ["-share_pct"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "facility"), name="unique_project_facility"
                    )
                ],
            },
        ),
    ]
