name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create and deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "carbomica-dashboard"
          heroku_email: "craigparker6@gmail.com"
          buildpack: "heroku/python"
          procfile: "true"
          usedocker: false
          stack: "heroku-22"
          formation: "web"
        env:
          HD_DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
          HD_DJANGO_DEBUG: "False"
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          
      - name: Install Heroku CLI
        run: npm install -g heroku
        
      - name: Set Heroku Config Vars
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku config:set DJANGO_SECRET_KEY="${{secrets.DJANGO_SECRET_KEY}}" --app carbomica-dashboard
          heroku config:set DJANGO_DEBUG=False --app carbomica-dashboard
          heroku config:set DISABLE_COLLECTSTATIC=1 --app carbomica-dashboard
          
      - name: Run Migrations
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku run python manage.py migrate --app carbomica-dashboard
